package backgammon;

import java.awt.FlowLayout;
import java.awt.Graphics;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author macbookpro
 */
public class Server extends javax.swing.JFrame implements Runnable, ActionListener{

    /**
     * Creates new form Server
     */
    static int hit = 0; // number of hits
    static boolean myTurn = true;  // is servers turn.
    static boolean isWin = false; // did he win.
    static ServerSocket ss; // creates a server socket
    static Socket s; // socket for client to connect on
    Thread t = new Thread(this); // thread of this class
    static PrintWriter out; // to send messages to client.
    static BufferedReader in ; // to recieve from client.
    panel p = new panel(); // instance of object panel.
    JButton roll = new JButton();
    int i;
    int j;
    Random rn = new Random();
    
    public Server() {
        super("Server");
        try {
            ss = new ServerSocket(8080);
            s = ss.accept();
            
        } catch (IOException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
        roll.setText("Roll Dice");
        roll.addActionListener(this);
        this.add(p);
        setSize(682, 800);
        this.add(roll);
        this.setVisible(true);
        initComponents();
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server().setVisible(true);
            }
        });
    }
    public static void sendMove(String s){
        out.println(s);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while(true){
            try {
                out = new PrintWriter(s.getOutputStream(), true);
                in = new BufferedReader(new InputStreamReader(s.getInputStream()));
                
                String clientMove;
                clientMove = in.readLine();
                System.out.println(clientMove);
                mimicMove(clientMove);
                if(p.isWin()){
                  JOptionPane.showMessageDialog(this,"you win");
                  this.dispose();
                }
            } catch (IOException ex) {
                Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if(myTurn){
            i = rn.nextInt((6 - 1) + 1) + 1;
            j = rn.nextInt((6 - 1) + 1) + 1;
       
            JOptionPane.showMessageDialog(this,"First Die = "+i);
            p.seti(i);
            //p.seti(j);
            sendMove(""+i);
            //sendMove(""+j);
            myTurn = false;
        }
    }
    
    public void mimicMove(String s){
        if(s.equalsIgnoreCase("1")){
            if(p.onec<6)p.onec++;
                myTurn =true;
                p.repaint();
        }
        if(s.equalsIgnoreCase("2")){
            if(p.twoc<5)p.twoc++;
                myTurn =true;
                p.repaint();
        }
        if(s.equalsIgnoreCase("3")){
            if(p.threec<4)p.threec++;
                myTurn =true;
                p.repaint();
        }
        if(s.equalsIgnoreCase("4")){
            if(p.fourc<3)p.fourc++;
            myTurn =true;
                p.repaint();
        }
        if(s.equalsIgnoreCase("5")){
            if(p.fivec<2)p.fivec++;
            myTurn =true;
                p.repaint();
        }
        if(s.equalsIgnoreCase("6")){
            if(p.sixc<1)p.sixc++;
            myTurn =true;
                p.repaint();
        }
    }
}
class panel extends javax.swing.JPanel{

    /**
     * Creates new form panel
     */
    Toolkit t = Toolkit.getDefaultToolkit(); 
    Image bg = t.getImage("bg.png");//sea
    Image checker = t.getImage("checker.png");//red house
    int i = 0;
    int one =0;
    int two =0;
    int three =0;
    int four =0;
    int five =0;
    int six =0;
    int onec =0;
    int twoc =0;
    int threec =0;
    int fourc = 0;
    int fivec =0;
    int sixc =0;

    public panel() {
        super(true);
        this.setSize(700, 962);
        this.setOpaque(false);
        initComponents();
    }
    @Override
        /**
     * draws all the images into the panel.
     * @param g 
     */
    public void paintComponent(Graphics g){//89 // 65
        g.drawImage(bg, 0, 0, this);
        for(int j =0; j<one;j++){
            g.drawImage(checker,40, 705, this);
        }
        ///////
        int x = 705;
        for(int j =0; j<two;j++){
            g.drawImage(checker,126, x, this);
            x = x - 65;
        }
        x = 705;
        ///////
        for(int j = 0; j<three;j++){
            g.drawImage(checker,215, x, this);
            x = x -65;
            
        }
        ///////
        x = 705;
        for(int j =0; j<four;j++){
            g.drawImage(checker,304, x, this);
            x = x -65;
        }
        ////
        x = 705;
        for(int j =0; j<five;j++){
            g.drawImage(checker,393, x, this);
            x = x -65;
        }
        ////
        x = 705;
        for(int j =0; j<six;j++){
            g.drawImage(checker,482, x, this);
            x = x-65;
        }
        
        ////////////////////////////
        int c = 30;
        for(int j =0; j<onec;j++){
            g.drawImage(checker,40, c, this);
            c = c+65;
        }
        ///////
        c = 30;
        for(int j =0; j<twoc;j++){
            g.drawImage(checker,125, c, this);
            c = c + 65;
        }
        c = 30;
        ///////
        for(int j = 0; j<threec;j++){
            g.drawImage(checker,215, c, this);
            c = c +65;
            
        }
        ///////
        c = 30;
        for(int j =0; j<fourc;j++){
            g.drawImage(checker,304, c, this);
            c = c +65;
        }
        ////
        c = 30;
        for(int j =0; j<fivec;j++){
            g.drawImage(checker,393, c, this);
            c = c +65;
        }
        ////
        c = 30;
        for(int j =0; j<sixc;j++){
            g.drawImage(checker,482, c, this);
            c = c+65;
        }
    }
    void seti(int i ){
       this.i = i;
       
       switch(this.i){
           case 1:if(one<1)one++;break;
           case 2:if(two<2)two++;break;
           case 3:if(three<3)three++;break;
           case 4:if(four<4)four++;break;
           case 5:if(five<5)five++;break;
           case 6:if(six<6)six++;break;    
       }
       repaint();
    }
    boolean isWin(){
        if(one == 1&&two ==2&& three ==3&&four==4&&five ==5&&six==6)
            return true;
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    // End of variables declaration                   

}
